name: NPM Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build on node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: yarn test
        env:
          CI: true

      - name: GitHub Test on Slack
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: Ilshidur/action-slack@1.6.2
        with:
          args: 'Resistor build has been tested'

      - name: Publish if version has been updated
        if: success()
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          tag_name: 'v%s'
          tag_message: 'v%s'
          create_tag: 'true'
          commit_pattern: "^Release (\\S+)"
          workspace: '.'
          publish_command: 'yarn'
          publish_args: '--non-interactive'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: GitHub Publish on Slack
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: Ilshidur/action-slack@1.6.2
        with:
          args: 'Resistor has been published'
